#:schema https://raw.githubusercontent.com/ghishadow/lapce-schema/main/volt.schema.json
name = "lapce-swift"
version = "0.1.3"
author = "syntacti"
display-name = "Swift"
description = "Swift for Lapce: powered by sourcekit-lsp"
wasm = "lapce-swift.wasm"
repository = "https://github.com/syntacti/lapce-swift"

icon = "assets/Swift_logo_color.webp"

[activation]
language = ["swift", "c", "cpp", "objective-c"]
workspace-contains = [
  "*/Package.swift",
  "*/*.c",
  "*/*.m",
  "*/*.h",
  "*/*.cpp",
  "*/*.hpp",
  ]


[config."volt.serverPath"]
default = ""
description = "Path to sourcekit-lsp"
