name = "lapce-swift"
version = "0.1.0"
author = "ghishadow"
display-name = "Swift"
description = "Swift for Lapce: powered by sourcekit-lsp"
wasm = "lapce-swift.wasm"

[activation]
language = ["swift"]
workspace-contains = ["*/Package.swift"]